# Role binding for the tesk task in postgres namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-postgres-rolebinding
  namespace: postgres
subjects:
  - kind: ServiceAccount
    name: cicd-test
    namespace: "{{NAMESPACE}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-postgres-test-task
