apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-apic-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: fixup-dockerfiles
      runAfter:
        - clone-git-source
      taskRef:
        name: run-script
      params:
        - name: script
          value: "products/bash/fixup-dockerfiles.sh"
        - name: params
          value: " -n {{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # MQ build for dev
    - name: build-mq
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageName
          value: "mq-ddd"
        - name: imageTag
          value: "latest"
        - name: dockerfile
          value: "MQ.Dockerfile"
        - name: contextPath
          value: ""
        - name: pvc
          value: "buildah-mq"
      workspaces:
        - name: git-source
          workspace: git-source

    # MQ deploy for dev
    - name: deploy-wait-mq
      runAfter:
        - build-mq
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "latest"
        - name: imageName
          value: "mq-ddd"
        - name: releaseName
          value: "mq-ddd-qm-dev"
        - name: releaseScript
          value: release-mq.sh
        - name: namespace
          value: "{{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # build all ace for dev
    - name: build-ace-int-server-ace-api
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-api"
        - name: dockerfile
          value: "ACE-API.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-api"
        - name: pvc
          value: "buildah-ace-api"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-acme
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-acme"
        - name: dockerfile
          value: "ACE-Acme.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-acme"
        - name: pvc
          value: "buildah-ace-acme"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-bernie
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: dockerfile
          value: "ACE-Bernie.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-bernie"
        - name: pvc
          value: "buildah-ace-bernie"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: build-ace-int-server-ace-chris
      runAfter:
        - fixup-dockerfiles
      taskRef:
        name: build-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-chris"
        - name: dockerfile
          value: "ACE-Chris.Dockerfile"
        - name: contextPath
          value: "Bar_files/ace-chris"
        - name: pvc
          value: "buildah-ace-chris"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace for dev
    - name: deploy-wait-ace-api
      runAfter:
        - build-ace-int-server-ace-api
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-api"
        - name: releaseName
          value: "ddd-dev-ace-api"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-bernie
      runAfter:
        - build-ace-int-server-ace-bernie
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: releaseName
          value: "ddd-dev-ace-bernie"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-acme
      runAfter:
        - build-ace-int-server-ace-acme
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-acme"
        - name: releaseName
          value: "ddd-dev-ace-acme"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: deploy-wait-ace-chris
      runAfter:
        - build-ace-int-server-ace-chris
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-chris"
        - name: releaseName
          value: "ddd-dev-ace-chris"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-dev"
      workspaces:
        - name: git-source
          workspace: git-source

    # test end-to-end API for dev
    - name: test-e2e-api-in-dev-namespace
      runAfter:
        - apic-resource-config-dev
        - deploy-wait-ace-chris
        - deploy-wait-mq
        - deploy-wait-ace-api
        - deploy-wait-ace-acme
        - deploy-wait-ace-bernie
      taskRef:
        name: api-test-e2e
      params:
        - name: suffix
          value: "ddd"
        - name: dddType
          value: "dev"
      workspaces:
        - name: git-source
          workspace: git-source

    # push ace images to test namespace
    - name: image-push-to-test-ace-chris
      runAfter:
        - test-e2e-api-in-dev-namespace
      taskRef:
        name: image-push-to-test
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-chris"
        - name: pvc
          value: "buildah-ace-chris"
    - name: image-push-to-test-ace-acme
      runAfter:
        - test-e2e-api-in-dev-namespace
      taskRef:
        name: image-push-to-test
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-acme"
        - name: pvc
          value: "buildah-ace-acme"
    - name: image-push-to-test-ace-bernie
      runAfter:
        - test-e2e-api-in-dev-namespace
      taskRef:
        name: image-push-to-test
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: pvc
          value: "buildah-ace-bernie"
    - name: image-push-to-test-ace-api
      runAfter:
        - test-e2e-api-in-dev-namespace
      taskRef:
        name: image-push-to-test
      params:
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageName
          value: "ddd-ace-api"
        - name: pvc
          value: "buildah-ace-api"

    # push mq image to test namespace
    - name: image-push-to-test-mq
      runAfter:
        - test-e2e-api-in-dev-namespace
      taskRef:
        name: image-push-to-test
      params:
        - name: imageTag
          value: "latest"
        - name: imageName
          value: "mq-ddd"
        - name: pvc
          value: "buildah-mq"

    # --------------------------------- IN TEST NAMESPACE ---------------------------------------------

    # Deploy MQ for test
    - name: deploy-wait-mq-test
      runAfter:
        - image-push-to-test-mq
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "latest-test"
        - name: imageName
          value: "mq-ddd"
        - name: releaseName
          value: "mq-ddd-qm-test"
        - name: releaseScript
          value: release-mq.sh
        - name: namespace
          value: "{{NAMESPACE}}"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace api for test
    - name: deploy-wait-ace-api-test
      runAfter:
        - image-push-to-test-ace-api
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)-test"
        - name: imageName
          value: "ddd-ace-api"
        - name: releaseName
          value: "ddd-test-ace-api"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-test"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace bernie in test namespace
    - name: deploy-wait-ace-bernie-test
      runAfter:
        - image-push-to-test-ace-bernie
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)-test"
        - name: imageName
          value: "ddd-ace-bernie"
        - name: releaseName
          value: "ddd-test-ace-bernie"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-test"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace acme for test
    - name: deploy-wait-ace-acme-test
      runAfter:
        - image-push-to-test-ace-acme
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)-test"
        - name: imageName
          value: "ddd-ace-acme"
        - name: releaseName
          value: "ddd-test-ace-acme"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-test"
      workspaces:
        - name: git-source
          workspace: git-source

    # deploy all ace chris for test
    - name: deploy-wait-ace-chris-test
      runAfter:
        - image-push-to-test-ace-chris
      taskRef:
        name: deploy-task
      params:
        - name: imageTag
          value: "$(params.imageTag)-test"
        - name: imageName
          value: "ddd-ace-chris"
        - name: releaseName
          value: "ddd-test-ace-chris"
        - name: releaseScript
          value: release-ace-integration-server.sh
        - name: namespace
          value: "{{NAMESPACE}}"
        - name: acePolicyProjectParam
          value: "-d policyproject-ddd-test"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: apic-resource-config-dev
      runAfter:
        - deploy-wait-ace-chris
        - deploy-wait-mq
        - deploy-wait-ace-api
        - deploy-wait-ace-acme
        - deploy-wait-ace-bernie
      taskRef:
        name: apic-resource-config
      params:
        - name: environment
          value: "dev"
        - name: releaseName
          value: "ademo"
        - name: releaseScript
          value: pub-sub-apic.sh
      workspaces:
        - name: git-source
          workspace: git-source

    - name: apic-resource-config-test
      runAfter:
        - test-e2e-api-in-dev-namespace
        - deploy-wait-ace-chris-test
        - deploy-wait-mq-test
        - deploy-wait-ace-api-test
        - deploy-wait-ace-acme-test
        - deploy-wait-ace-bernie-test
      taskRef:
        name: apic-resource-config
      params:
        - name: environment
          value: "test"
        - name: releaseName
          value: "ademo"
        - name: releaseScript
          value: pub-sub-apic.sh
      workspaces:
        - name: git-source
          workspace: git-source

    # test end-to-end API for test
    - name: test-e2e-api-in-test-namespace
      runAfter:
        - apic-resource-config-test
        - deploy-wait-ace-chris-test
        - deploy-wait-mq-test
        - deploy-wait-ace-api-test
        - deploy-wait-ace-acme-test
        - deploy-wait-ace-bernie-test
      taskRef:
        name: api-test-e2e
      params:
        - name: suffix
          value: "ddd"
        - name: dddType
          value: "test"
      workspaces:
        - name: git-source
          workspace: git-source
